#%RAML 1.0 DataType
type: object
properties:
  customerId:
    type: string
    required: false
  customerEmailId:
    type: string  
    required: false
  Items:
    type: object
    required: true
  Cart_Total_Amount:
    type: number
    required: true  