https:
  port: "8082"
  readTimeout: "30000"
tls:
  keyStoreType: "JKS"
  keyPath: "keystore.jks"
  alias: "mule"
  
base:
  path: "/api"

expcustomerPortal:
  path: "/api/*"
  
ping:
  apiName: "EAPI CustomerPortal Api "
  projectVersion: "1.0.7"
  apiVersion: "1.0.7"
  env: "SANDBOX"
  server: "mule.server"
  serviceType: "exp-customerPortal"
  status: "200"
  statusMessage: "Up"
  message: "Alive"
  x-dependent-ping: "true"
  
  
  