{
  "apiName": "exp-customerPortal",
  "apiVersion": "v1.0.3",
  "server": "mule.server",
  "serviceHealth": {
    "serviceType": "exp-customerPortal",
    "status": "UP",
    "message": "Alive"
  }
}